# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(756, 860)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(1500, 1500))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Statuslabel = QtWidgets.QLabel(self.frame_3)
        self.Statuslabel.setMaximumSize(QtCore.QSize(140, 16777215))
        self.Statuslabel.setObjectName("Statuslabel")
        self.horizontalLayout_3.addWidget(self.Statuslabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_3)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 698, 608))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imageLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.imageLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.imageLabel.setObjectName("imageLabel")
        self.horizontalLayout_2.addWidget(self.imageLabel)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(279, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 4, 0, 1, 1)
        self.StatusComboBox = QtWidgets.QComboBox(self.frame_3)
        self.StatusComboBox.setMaximumSize(QtCore.QSize(200, 30))
        self.StatusComboBox.setObjectName("StatusComboBox")
        self.StatusComboBox.addItem("")
        self.StatusComboBox.addItem("")
        self.StatusComboBox.addItem("")
        self.StatusComboBox.addItem("")
        self.StatusComboBox.addItem("")
        self.StatusComboBox.addItem("")
        self.gridLayout_3.addWidget(self.StatusComboBox, 3, 1, 1, 1)
        self.submitButton = QtWidgets.QPushButton(self.frame_3)
        self.submitButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.submitButton.setObjectName("submitButton")
        self.gridLayout_3.addWidget(self.submitButton, 4, 1, 1, 1)
        self.imageDesciriptionTextEdit = QtWidgets.QTextEdit(self.frame_3)
        self.imageDesciriptionTextEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.imageDesciriptionTextEdit.setObjectName("imageDesciriptionTextEdit")
        self.gridLayout_3.addWidget(self.imageDesciriptionTextEdit, 2, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.previousButton = QtWidgets.QPushButton(self.frame_3)
        self.previousButton.setMinimumSize(QtCore.QSize(150, 0))
        self.previousButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout.addWidget(self.previousButton)
        self.resizeSlider = QtWidgets.QSlider(self.frame_3)
        self.resizeSlider.setMinimum(1)
        self.resizeSlider.setMaximum(10)
        self.resizeSlider.setProperty("value", 7)
        self.resizeSlider.setSliderPosition(7)
        self.resizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.resizeSlider.setObjectName("resizeSlider")
        self.horizontalLayout.addWidget(self.resizeSlider)
        self.nextButton = QtWidgets.QPushButton(self.frame_3)
        self.nextButton.setMinimumSize(QtCore.QSize(150, 0))
        self.nextButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.gridLayout_2.addWidget(self.frame_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Statuslabel.setText(_translate("MainWindow", "Osztályozó címke"))
        self.imageLabel.setText(_translate("MainWindow", "TextLabel"))
        self.StatusComboBox.setItemText(0, _translate("MainWindow", "Nem meghatározott"))
        self.StatusComboBox.setItemText(1, _translate("MainWindow", "Nincs vályú"))
        self.StatusComboBox.setItemText(2, _translate("MainWindow", "Nincs embrió"))
        self.StatusComboBox.setItemText(3, _translate("MainWindow", "Nem kelt ki"))
        self.StatusComboBox.setItemText(4, _translate("MainWindow", "Nem él"))
        self.StatusComboBox.setItemText(5, _translate("MainWindow", "Több embrió"))
        self.submitButton.setText(_translate("MainWindow", "Rögzítés"))
        self.imageDesciriptionTextEdit.setPlaceholderText(_translate("MainWindow", "Adjon meg egy leírást a képhez"))
        self.previousButton.setText(_translate("MainWindow", "Előző"))
        self.nextButton.setText(_translate("MainWindow", "Következő"))

