# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(426, 666)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_2)
        self.tabWidget.setMaximumSize(QtCore.QSize(450, 16777215))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.imageListWidget = QtWidgets.QListWidget(self.tab)
        self.imageListWidget.setObjectName("imageListWidget")
        self.gridLayout_5.addWidget(self.imageListWidget, 7, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.surveyTextEdit = QtWidgets.QTextEdit(self.tab)
        self.surveyTextEdit.setMaximumSize(QtCore.QSize(250, 100))
        self.surveyTextEdit.setObjectName("surveyTextEdit")
        self.horizontalLayout_5.addWidget(self.surveyTextEdit)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.subSurveyTextBox = QtWidgets.QTextEdit(self.tab)
        self.subSurveyTextBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.subSurveyTextBox.setObjectName("subSurveyTextBox")
        self.horizontalLayout_13.addWidget(self.subSurveyTextBox)
        self.gridLayout_5.addLayout(self.horizontalLayout_13, 4, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem = QtWidgets.QSpacerItem(429, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.listButton = QtWidgets.QPushButton(self.tab)
        self.listButton.setObjectName("listButton")
        self.horizontalLayout_12.addWidget(self.listButton)
        self.gridLayout_5.addLayout(self.horizontalLayout_12, 5, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.preProcessedCheckBox = QtWidgets.QCheckBox(self.tab)
        self.preProcessedCheckBox.setObjectName("preProcessedCheckBox")
        self.horizontalLayout_14.addWidget(self.preProcessedCheckBox)
        self.gridLayout_5.addLayout(self.horizontalLayout_14, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.subSurveyComboBox = QtWidgets.QComboBox(self.tab)
        self.subSurveyComboBox.setMaximumSize(QtCore.QSize(300, 30))
        self.subSurveyComboBox.setEditable(True)
        self.subSurveyComboBox.setObjectName("subSurveyComboBox")
        self.horizontalLayout_7.addWidget(self.subSurveyComboBox)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.surveyComboBox = QtWidgets.QComboBox(self.tab)
        self.surveyComboBox.setMaximumSize(QtCore.QSize(300, 30))
        self.surveyComboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.surveyComboBox.setObjectName("surveyComboBox")
        self.horizontalLayout_6.addWidget(self.surveyComboBox)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 6, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.newSurveyDescriptionTextEdit = QtWidgets.QTextEdit(self.tab_2)
        self.newSurveyDescriptionTextEdit.setMaximumSize(QtCore.QSize(350, 16777215))
        self.newSurveyDescriptionTextEdit.setObjectName("newSurveyDescriptionTextEdit")
        self.horizontalLayout_4.addWidget(self.newSurveyDescriptionTextEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 2, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.newSurveyPathLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.newSurveyPathLineEdit.setMaximumSize(QtCore.QSize(347, 20))
        self.newSurveyPathLineEdit.setObjectName("newSurveyPathLineEdit")
        self.horizontalLayout_2.addWidget(self.newSurveyPathLineEdit)
        self.toolButton = QtWidgets.QToolButton(self.tab_2)
        self.toolButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.newSurveyNameLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.newSurveyNameLineEdit.setMaximumSize(QtCore.QSize(355, 16777215))
        self.newSurveyNameLineEdit.setObjectName("newSurveyNameLineEdit")
        self.horizontalLayout_3.addWidget(self.newSurveyNameLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 1, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.modifySurveyDescriptionButton = QtWidgets.QPushButton(self.tab_2)
        self.modifySurveyDescriptionButton.setObjectName("modifySurveyDescriptionButton")
        self.horizontalLayout_8.addWidget(self.modifySurveyDescriptionButton)
        self.deleteSurveyButton = QtWidgets.QPushButton(self.tab_2)
        self.deleteSurveyButton.setObjectName("deleteSurveyButton")
        self.horizontalLayout_8.addWidget(self.deleteSurveyButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_8.addWidget(self.pushButton_2)
        self.gridLayout_6.addLayout(self.horizontalLayout_8, 3, 0, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 4, 0, 1, 1)
        self.surveyListWidget = QtWidgets.QListWidget(self.tab_2)
        self.surveyListWidget.setObjectName("surveyListWidget")
        self.gridLayout_6.addWidget(self.surveyListWidget, 5, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.parentSurveyComboBox = QtWidgets.QComboBox(self.tab_3)
        self.parentSurveyComboBox.setObjectName("parentSurveyComboBox")
        self.horizontalLayout_11.addWidget(self.parentSurveyComboBox)
        self.gridLayout_7.addLayout(self.horizontalLayout_11, 0, 0, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 1, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.newSubSurveyPathLineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.newSubSurveyPathLineEdit.setObjectName("newSubSurveyPathLineEdit")
        self.horizontalLayout_10.addWidget(self.newSubSurveyPathLineEdit)
        self.toolButton_2 = QtWidgets.QToolButton(self.tab_3)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_10.addWidget(self.toolButton_2)
        self.gridLayout_7.addLayout(self.horizontalLayout_10, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 2, 0, 1, 2)
        self.newSubSurveyNameLineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.newSubSurveyNameLineEdit.setObjectName("newSubSurveyNameLineEdit")
        self.gridLayout_7.addWidget(self.newSubSurveyNameLineEdit, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 3, 0, 1, 1)
        self.newSubSurveyDescriptionTextEdit = QtWidgets.QTextEdit(self.tab_3)
        self.newSubSurveyDescriptionTextEdit.setObjectName("newSubSurveyDescriptionTextEdit")
        self.gridLayout_7.addWidget(self.newSubSurveyDescriptionTextEdit, 3, 1, 1, 2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.modifySubSurveyDescriptionButton = QtWidgets.QPushButton(self.tab_3)
        self.modifySubSurveyDescriptionButton.setObjectName("modifySubSurveyDescriptionButton")
        self.horizontalLayout_9.addWidget(self.modifySubSurveyDescriptionButton)
        self.deleteSubSurveyButton = QtWidgets.QPushButton(self.tab_3)
        self.deleteSubSurveyButton.setObjectName("deleteSubSurveyButton")
        self.horizontalLayout_9.addWidget(self.deleteSubSurveyButton)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_9.addWidget(self.pushButton_4)
        self.gridLayout_7.addLayout(self.horizontalLayout_9, 4, 0, 1, 3)
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 5, 0, 1, 1)
        self.subSurveyListWidget = QtWidgets.QListWidget(self.tab_3)
        self.subSurveyListWidget.setObjectName("subSurveyListWidget")
        self.gridLayout_7.addWidget(self.subSurveyListWidget, 6, 0, 1, 3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.imageListWidget_2 = QtWidgets.QListWidget(self.tab_4)
        self.imageListWidget_2.setObjectName("imageListWidget_2")
        self.gridLayout_4.addWidget(self.imageListWidget_2, 8, 0, 1, 1)
        self.drawButton = QtWidgets.QPushButton(self.tab_4)
        self.drawButton.setMinimumSize(QtCore.QSize(0, 30))
        self.drawButton.setObjectName("drawButton")
        self.gridLayout_4.addWidget(self.drawButton, 1, 0, 1, 1)
        self.homomorphicButton = QtWidgets.QPushButton(self.tab_4)
        self.homomorphicButton.setMinimumSize(QtCore.QSize(0, 30))
        self.homomorphicButton.setObjectName("homomorphicButton")
        self.gridLayout_4.addWidget(self.homomorphicButton, 4, 0, 1, 1)
        self.modifyButton = QtWidgets.QPushButton(self.tab_4)
        self.modifyButton.setMinimumSize(QtCore.QSize(0, 30))
        self.modifyButton.setObjectName("modifyButton")
        self.gridLayout_4.addWidget(self.modifyButton, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 5, 0, 1, 1)
        self.detectAndDrawButton = QtWidgets.QPushButton(self.tab_4)
        self.detectAndDrawButton.setMinimumSize(QtCore.QSize(0, 30))
        self.detectAndDrawButton.setObjectName("detectAndDrawButton")
        self.gridLayout_4.addWidget(self.detectAndDrawButton, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 7, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.pushButton_8)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.gridLayout_4.addLayout(self.horizontalLayout, 6, 0, 1, 2)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kezelő felület"))
        self.label_3.setText(_translate("MainWindow", "Vizsgálat leírása"))
        self.label_13.setText(_translate("MainWindow", "Részvizsgálat leírása"))
        self.listButton.setText(_translate("MainWindow", "Listázás"))
        self.preProcessedCheckBox.setText(_translate("MainWindow", "Előfeldolgozott"))
        self.label_2.setText(_translate("MainWindow", "Részvizsgálat"))
        self.label.setText(_translate("MainWindow", "Vizsgálat"))
        self.label_6.setText(_translate("MainWindow", "Képek"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Képek"))
        self.label_11.setText(_translate("MainWindow", "Leírás"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.label_9.setText(_translate("MainWindow", "Vizsgálat neve"))
        self.label_10.setText(_translate("MainWindow", "Elérési útvonal"))
        self.modifySurveyDescriptionButton.setText(_translate("MainWindow", "Leírás módosítása"))
        self.deleteSurveyButton.setText(_translate("MainWindow", "Törlés"))
        self.pushButton_2.setText(_translate("MainWindow", "Felvétel"))
        self.label_15.setText(_translate("MainWindow", "Vizsgálatok"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Vizsgálatok"))
        self.label_12.setText(_translate("MainWindow", "Vizsgálat neve"))
        self.label_8.setText(_translate("MainWindow", "Elérési útvonal"))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.label_7.setText(_translate("MainWindow", "Részvizsgálat neve"))
        self.label_4.setText(_translate("MainWindow", "Leírás"))
        self.modifySubSurveyDescriptionButton.setText(_translate("MainWindow", "Leírás módosítása"))
        self.deleteSubSurveyButton.setText(_translate("MainWindow", "Törlés"))
        self.pushButton_4.setText(_translate("MainWindow", "Felvétel"))
        self.label_14.setText(_translate("MainWindow", "Részvizsgálatok"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Részvizsgálatok"))
        self.drawButton.setText(_translate("MainWindow", "Perem berajzolás"))
        self.homomorphicButton.setText(_translate("MainWindow", "Homomorfiaszűrés"))
        self.modifyButton.setText(_translate("MainWindow", "Perem módosítás"))
        self.label_5.setText(_translate("MainWindow", "Kijelölés megadása"))
        self.detectAndDrawButton.setText(_translate("MainWindow", "Peremdetektálás"))
        self.label_16.setText(_translate("MainWindow", "Képek"))
        self.pushButton_7.setText(_translate("MainWindow", "Összes"))
        self.pushButton_8.setText(_translate("MainWindow", "Megszüntetés"))
        self.pushButton_3.setText(_translate("MainWindow", "Invertálás"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Előfeldolgozás"))

